version: '3.7'

services:
  app:
    build: .
    command: yarn run dev
    container_name: api_hapijs
    depends_on:
      - db
    links:
      - db
    networks:
      - app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  db:
    container_name: db_hapijs
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

networks:
  app:
volumes:
  db_data:
