version: '3.7'

services:
  app:
    build: .
    command: yarn run dev
    container_name: api_hapijs
    depends_on:
      - db
    links:
      - db
    networks:
      - app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

  db:
    container_name: db_hapijs
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

networks:
  app:
volumes:
  db_data:
